<?php

namespace adminBundle\Repository;

/**
 * countriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class countriesRepository extends \Doctrine\ORM\EntityRepository
{
}
