<?php

namespace adminBundle\Repository;

/**
 * currencyratesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class currencyratesRepository extends \Doctrine\ORM\EntityRepository
{
}
