<?php

namespace adminBundle\Repository;

/**
 * currenciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class currenciesRepository extends \Doctrine\ORM\EntityRepository
{
}
