<?php

namespace adminBundle\Repository;

/**
 * districtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class districtsRepository extends \Doctrine\ORM\EntityRepository
{
}
