<?php

namespace adminBundle\Repository;

/**
 * roomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roomsRepository extends \Doctrine\ORM\EntityRepository
{
}
