<?php

namespace adminBundle\Repository;

/**
 * roomratesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roomratesRepository extends \Doctrine\ORM\EntityRepository
{
}
