<?php

namespace adminBundle\Repository;

/**
 * seasonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seasonsRepository extends \Doctrine\ORM\EntityRepository
{
}
